version: 2

jobs:
  install:
    docker:
      - image: circleci/node:10-browsers
    steps:
      - checkout
      - run:
          name: "Install dependencies"
          command: yarn
      - save_cache:
          key: dependency-cache-{{ .Branch }}-{{ checksum "yarn.lock" }}-{{ .Revision }}
          paths:
            - node_modules
  install-prod:
    docker:
      - image: circleci/node:10-browsers
    environment:
      - NODE_ENV: "production"
    steps:
      - checkout
      - run:
          name: "Install production dependencies"
          command: yarn
      - save_cache:
          key: dependency-prod-cache-{{ .Branch }}-{{ checksum "yarn.lock" }}-{{ .Revision }}
          paths:
            - node_modules
  test:
    docker:
      - image: circleci/node:10-browsers
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ .Branch }}-{{ checksum "yarn.lock" }}-{{ .Revision }}
      - run:
          name: "Run unit tests"
          command: yarn test
      - store_artifacts:
          path: ./coverage
  lint:
    docker:
      - image: circleci/node:10-browsers
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ .Branch }}-{{ checksum "yarn.lock" }}-{{ .Revision }}
      - run:
          name: "Run linters"
          command: yarn lint
  build-local:
    docker:
      - image: circleci/node:10-browsers
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ .Branch }}-{{ checksum "yarn.lock" }}-{{ .Revision }}
      - run:
          name: "Build Local"
          command: yarn build:local
  build-dev:
    docker:
      - image: circleci/node:10-browsers
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ .Branch }}-{{ checksum "yarn.lock" }}-{{ .Revision }}
      - run:
          name: "Build Development"
          command: yarn build:dev
  build-prod:
    docker:
      - image: circleci/node:10-browsers
    environment:
      - NODE_ENV: "production"
    steps:
      - checkout
      - restore_cache:
          key: dependency-prod-cache-{{ .Branch }}-{{ checksum "yarn.lock" }}-{{ .Revision }}
      - run:
          name: "Build Production"
          command: yarn build:prod

workflows:
  version: 2
  test-and-build:
    jobs:
      - install
      - install-prod
      - test:
          requires:
            - install
      - lint:
          requires:
            - install
      - build-local:
          requires:
            - test
            - lint
      - build-dev:
          requires:
            - test
            - lint
      - build-prod:
          requires:
            - install-prod
